definitions:
  controller.Controller:
    type: object
info:
  contact: {}
paths:
  /acc/v01/PutName:
    put:
      consumes:
      - application/json
      description: api test를 위한 기능
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      - description: User age
        in: path
        name: age
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call PutName, return ok by json
  /acc/v01/ok:
    get:
      consumes:
      - application/json
      description: api test를 위한 기능
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call GetOK, return ok by json
  /acc/v01/post:
    post:
      consumes:
      - application/json
      description: api test를 위한 기능
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      - description: User age
        in: path
        name: age
        required: true
        type: string
      - description: User pum
        in: path
        name: pnum
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Controller'
      summary: call Post, return ok by json
swagger: "2.0"
